#!/usr/bin/env bash

# Default settings

# When reading xdg menus if not "gnome-" or "kde-" xpra fails!
export XDG_MENU_PREFIX="gnome-" 
SCALING_FACTOR=2
USE_OPENGL="auto"
PERFORMANCE_OPTIONS="--encoding=rgb --mmap=yes --compress=0"

# this gets setup just before we start xpra, so that we make sure it's stopped if possible
function cleanup {
  echo "Making sure xpra is stopped"
  xpra stop "$DISPLAYNUM" >/dev/null 2>&1
}

print_help() {
    echo "Usage: run_scaled [--scale=scaling_factor] [--opengl=auto|yes|no] application"
    echo ""
    echo "--scale  Sets the factor the application is scaled by. Fractional scales are"
    echo "         supported. It is set to 2 by default."
    echo "--opengl Sets whether xpra should use opengl for rendering. If you get rendering"
    echo "         errors, especially when the window is resized, try setting it to no. It"
    echo "         is set to auto by default."
    echo ""
}

if [ $# = 0 ]
    then print_help
        exit 1
fi

while true
    do if [ $# -gt 0 ]
        then case $1 in
            --scale=*)
                SCALING_FACTOR="${1#*=}"
                shift
            ;;
            --opengl=*)
                USE_OPENGL="${1#*=}"
                shift
            ;;
            --)
                shift
                break
            ;;
            --*)
                print_help
                exit 1
            ;;
            *)
                break
            ;;
        esac
    else
        echo "No application given!"
        exit 2
    fi
done

declare -i UNSCALED_RESOLUTION_X
declare -i UNSCALED_RESOLUTION_Y
UNSCALED_RESOLUTION_X=$(xrandr | sed -n -e 's/Screen 0:.*current \([0-9][0-9]*\) x \([0-9][0-9]*\).*/\1/p')
UNSCALED_RESOLUTION_Y=$(xrandr | sed -n -e 's/Screen 0:.*current \([0-9][0-9]*\) x \([0-9][0-9]*\).*/\2/p')

UNSCALED_RESOLUTION="$( awk "BEGIN {print int($UNSCALED_RESOLUTION_X / $SCALING_FACTOR) \"x\" int($UNSCALED_RESOLUTION_Y / $SCALING_FACTOR)}" /dev/null )"

#--start-new-commands=no causes xpra to not even try to read xdg menus, starting up much faster, and not running into the gnome- bug mentioned above

DISPLAYNUM=:$(shuf -i 10000-99999999 -n 1)

# setup the trap to cleanup xpra
trap cleanup EXIT

ESCAPED_PARAMS=$(printf '%q ' "$@")
xpra start "$DISPLAYNUM" --xvfb="Xvfb +extension Composite -screen 0 ${UNSCALED_RESOLUTION}x24+32 -nolisten tcp -noreset  -auth \$XAUTHORITY" --env=GDK_SCALE=1 --env=GDK_DPI_SCALE=1 --env=QT_SCALE_FACTOR=1 --env=QT_AUTO_SCREEN_SCALE_FACTOR=0 --start-child="$ESCAPED_PARAMS" --exit-with-children --start-new-commands=no

until xpra info "$DISPLAYNUM" >/dev/null 2>&1; do
  sleep 0.1
done

XGDK_SCALE=1 PRA_EXPORT_ICON_DATA=0 xpra attach "$DISPLAYNUM" "--desktop-scaling=$SCALING_FACTOR" "--opengl=$USE_OPENGL" $PERFORMANCE_OPTIONS || xpra stop "$DISPLAYNUM"
